Forecast and Replay Model Fields:
  Forecast:
    Base URI: "/cf/api/fcast/"
    collections: ["fcast", "assim"]
    datakey: ["aqc_slv", "chm_slv", "chm_v72","met_slv","met_v72"]
    product: ["CO", "NO2", "O3", "PM25", "SO2", "HCHO", "MET"]
    lat: "float value of some latitude"
    lon: "float value of some longitude"
    start_date: "YYYYMMDD or latest"
    end_date: "YYYYMMDD or empty if start_date is latest"
    Default Values:
      collection: "fcast"
      level: "v1"
      product: "NO2"
      lat: "38.9"
      lon: "-77.0"
      start_date: "latest"
      end_date: "None"

  Assimilation/Replay:
    Base URI: "/cf/api/assim/"
    collections: ["fcast", "assim"]
    level: ["x1", "v72"]
    lat: "float value of some latitude"
    lon: "float value of some longitude"
    start_date: "YYYYMMDD or latest"
    end_date: "YYYYMMDD or empty if start_date is latest"
    Default Values:
      collection: "fcast"
      level: "x1"
      lat: "38.9"
      lon: "-77.0"
      start_date: "latest"
      end_date: "None"

Historical AQC Data Sets:
  All Data:
    Base URI: "/cfapi/aqc/<collection>/<product>/<lat>x<lon>/<start_date>/<end_date>/"
    collections: ["fcast", "assim"]
    products: ["NO2", "O3", "PM25"]
    start_date: "YYYYMMDD or latest"
    end_date: "YYYYMMDD or empty if start_date is latest"
    Default Values:
      collection: "assim"
      product: "NO2"
      lat: "38.9"
      lon: "-77.0"
      start_date: "latest"
      end_date: "None"
