[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[project]
name = "EarthNow"                 # distribution name on PyPI / installers
version = "0.1.0"
description = "WxMaps plotting + products + data readers"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Bill Putman, Tools Team (Package by Sandra Roberts)" }]

dependencies = [
  "numpy>=1.23",
  "netCDF4>=1.6.0",
  "scipy>=1.10",
  "pytz",
  "pillow>=10",
  "matplotlib>=3.7",
  "cartopy>=0.22",
  "astropy",
  "shapely",
  "pandas",
  "geopandas",
]

[project.optional-dependencies]
# plotting = [
# ]

# images = [
# ]

dev = [
  "pytest>=7",
  "ruff>=0.3",
  "mypy>=1.7",
  "ipykernel>=7.2.0",
  "xarray>=2026.2.0", # This is just for testing right now, but move to main dependencies if we transition to xarray reading
  "pre-commit>=4.5.1",
]

# uv_build file selection (recommended for flat layout repos)
[tool.uv.build-backend]
include = ["src/**"]
exclude = [
  "**/__pycache__/**",
  "**/*.pyc",
  "**/.DS_Store",
  "test*.py",
]
