SHELL = /bin/bash
MAIN = FLEXTRA_ECMWF
INCF	= incl* 
#

INCPATH  = /nilu2/home/flexpart/lib64/absoft/include
LIBPATH1 = /nilu2/home/flexpart/lib64/absoft/lib
LIBPATH2 = /nilu2/home/flexpart/lib64/absoft/lib
FFLAGS   =   -O2 -s -I$(INCPATH) -p$(INCPATH) -m64 -mcmodel=medium
#FFLAGS   =  -g -Rb -Rc -Rs  -s  -I$(INCPATH) -p$(INCPATH) -m64 -mcmodel=medium
LDFLAGS  = $(FFLAGS) -L$(LIBPATH2) -L$(LIBPATH1) -lgrib_api_f90 -lgrib_api -lm -ljasper
#

OBJECTS = caldate.o                openoutput.o \
          checklimits.o            coordtrafo.o \
          orolininterpol.o         etatrafo.o \
          petters.o eta.ecmwf.o    FLEXTRA.o \
          pp.ecmwf.o               geteta.o \
          getfields.o              pvinterpol.o \
          getheight.o              random.o \
          readavailable.o          getwind.o \
          readcommand.o            gridcheck.o \
          inter3d.o                readoro.o \
          interisentrop.o          readpaths.o \
          interisobar.o            readpoints.o \
          intermix.o               readwind.o \
          intermod.o               subtractoro.o \
          interpol.o               timemanager.o \
          juldate.o                trajinterpol.o \
          lamphi_ecmwf.o           trajout.o  \
          lastprocessor.o          uncertcoor.o \
          levinterpol.o            utransform.o \
          levlininterpol.o         vtransform.o \
          lininterpol.o            wtransform.o \
          numerical.o              zztrafo.o \
          cmapf1.0.o               gridcheck_nests.o \
          readwind_nests.o         lininterpol_nests.o \
          levlininterpol_nests.o   orolininterpol_nests.o \
          interpol_nests.o         levinterpol_nests.o \
          skplin.o                 readcet.o \
          opencetoutput.o openflightoutput.o \
          readflight.o             calcpv.o \
          getmet.o                 calcpv_nests.o \
          swap32.o                 ew.o


$(MAIN): $(OBJECTS)
	$(FC) *.o -o $(MAIN) $(LDFLAGS)
$(OBJECTS): $(INCF)

