SHELL = /bin/bash
MAIN = FLEXTRA_GFS
INCF	= incl* 
#

FC       = /opt/absoft/bin/f95
INCPATH  = /nilu/home/flexpart/lib/grib_api/include
LIBPATH1 = /nilu/home/flexpart/lib/grib_api/lib
LIBPATH2 = /nilu/home/flexpart/lib/jasper/lib
#FFLAGS   =   -s  -B108  -YEXT_NAMES=LCS -I$(INCPATH)
FFLAGS   =  -g -Rb -Rc -Rs  -s  -B108  -YEXT_NAMES=LCS -I$(INCPATH) -p$(INCPATH)
LDFLAGS  = $(FFLAGS)  -L$(LIBPATH1) -L$(LIBPATH2) -lgrib_api_f77 -lgrib_api -lm -ljasper
#

OBJECTS = caldate.o                openoutput.o \
          checklimits.o            coordtrafo.o \
          orolininterpol.o         etatrafo.o \
          petters.o eta.ecmwf.o    FLEXTRA.o \
          pp.ecmwf.o               geteta.o \
          getfields.o              pvinterpol.o \
          getheight.o              random.o \
          readavailable.o          getwind.o \
          readcommand.o            gridcheck_gfs.o \
          inter3d.o                readoro.o \
          interisentrop.o          readpaths.o \
          interisobar.o            readpoints.o \
          intermix.o               readwind_gfs.o \
          intermod.o               subtractoro.o \
          interpol.o               timemanager.o \
          juldate.o                trajinterpol.o \
          lamphi_ecmwf.o           trajout.o  \
          lastprocessor.o          uncertcoor.o \
          levinterpol.o            utransform.o \
          levlininterpol.o         vtransform.o \
          lininterpol.o            wtransform.o \
          numerical.o              zztrafo.o \
          cmapf1.0.o               gridcheck_nests_gfs.o \
          readwind_nests_gfs.o     lininterpol_nests.o \
          levlininterpol_nests.o   orolininterpol_nests.o \
          interpol_nests.o         levinterpol_nests.o \
          skplin.o                 readcet.o \
          opencetoutput.o          openflightoutput.o \
          readflight.o             calcpv.o \
          getmet.o                 calcpv_nests.o \
          swap32.o                 ew_gfs.o


$(MAIN): $(OBJECTS)
	$(FC) *.o -o $(MAIN) $(LDFLAGS)
$(OBJECTS): $(INCF)

