#BASE_PATH: /discover/nobackup/dao_ops/jardizzo/EarthNow/plots
#NPROC: 28
BASE_PATH: /discover/nobackup/$USER/EarthNow/plots
NPROC: 1

plot_current:
  products: [RainSnow, T2m, Vort500, Wind10m, Wind250]
  data_readers: [geos_cycled_replay]
  regions: [global, conus]
  nproc: $NPROC

products:
   RainSnow: # I don't think this product is complete, comment out for now
     product: rain_snow_accumulation_total_EarthNow
     style: light
     driver: "plotall.py"
     base-path: $BASE_PATH
  T2m:
    product: temperature_2m_EarthNow
    style: empty
    driver: "plotall.py"
    base-path: $BASE_PATH
  Vort500:
    product: vorticity_heights_500mb_EarthNow
    style: greytopo
    driver: "plotall.py"
    base-path: $BASE_PATH
  Wind10m:
    product: winds_10m_EarthNow
    style: light_states # Create "Blank" style?
    driver: "plotall.py"
    base-path: $BASE_PATH
  Wind250:
    product: winds_heights_250mb_EarthNow
    style: greyblue
    driver: "plotall.py"
    base-path: $BASE_PATH
  HelicityMaxReflectivity:
    product: max_reflectivity_EarthNow
    style: helicity
    driver: "plotall.py"
    base-path: $BASE_PATH
  Cape:
    product: cape_EarthNow
    style: greyblue
    driver: "plotall.py"
    base-path: $BASE_PATH
  Aerosols:
    product: aerosol_EarthNow
    style: greyblue
    driver: "plotall.py"
    base-path: $BASE_PATH
  Carbon:
    product: carbon_EarthNow
    style: greyblue
    driver: "plotall.py"
    base-path: $BASE_PATH
  Geocolor:
    product: geocolor_rgb_EarthNow
    style: satellite
    driver: "plotall.py"
    base-path: $BASE_PATH



data_readers:
  geos_cycled_replay:
    data-reader: geos_cycled_replays
    fdate: PT0H
