name: Black Code Formatter Check

on:
  pull_request:
    branches:
      - main

jobs:
  black-check:
    name: Run Black Formatter Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Black
        run: pip install black==26.1.0

      - name: Get changed Python files
        id: changed-files
        run: |
        CHANGED=$(git diff --name-only --diff-filter=ACM origin/${{ github.base_ref }}...HEAD -- '*.py')
        echo "files=$CHANGED" >> $GITHUB_OUTPUT

      - name: Run Black check
        if: steps.changed-files.outputs.files != ''
        run: echo "${{ steps.changed-files.outputs.files }}" | xargs black --check
